on:
  workflow_dispatch:
  push:
    branches:
      - main
      - stage
      - feature/**
      - bugfix/**
      - fix/**
      - hotfix/**
      - release/**
      - dependabot/**
      - renovate/**
      - chore/**
      - test/**

jobs:
  call-auto-merge:
    uses: variablesoftware/github-actions-setup-and-test/.github/workflows/auto-merge.yml@main
    with:
      # any workflow inputs
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    env:
      # any environment variables
